name: Tests

on: [push, pull_request]


jobs:
  test:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.6, 3.7, 3.8, 3.9, 3.10]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install -U pip wheel
          pip install -r requirements.txt

      - name: Install test dependencies
        run: pip install pytest

      - name: Run test with pytest
        run: python -m pytest
